### ISSUE TITLE
OAuth not handling expired certificates correctly

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#217]
Expired certificates are not handled correctly. This was seen when using the web app to load CMIP5 data with an expired certificate. Requests failed with a plain GET then when a GET with the expired certificate was execute the following error appeared:

```python
[INFO][2019-07-09 20:55:20,742][esgf.py[check_access:141]] Checking access with 'http://aims3.llnl.gov/thredds/dodsC/cmip5_css02_data/cmip5/output1/CMCC/CMCC-CM/decadal1985/mon/atmos/Amon/r1i2p1/tas/1/tas_Amon_CMCC-CM_decadal1985_r1i2p1_198511-199512.nc.dds'
[ERROR][2019-07-09 20:55:20,766][esgf.py[check_access:148]] Connection error 'aims3.llnl.gov'
Traceback (most recent call last):                                                                                
  File "/opt/conda/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()                                             
  File "/opt/conda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/opt/conda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/opt/conda/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)  
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate expired')]
```
The expired certificate should be detected, if the user authorized through myproxyclient they should receive and error, if the user authorized through oauth2 then an attempt should be made to refresh the token and grab a new certificate.

**Comment by jasonb5** [comment]
A fix has been added waiting to test.

**Comment by jasonb5** [comment]
Fixed in devel.
