### ISSUE TITLE
Fails to subset "hist_interval" axis.

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#219]
Dataset id: 

CMIP6.LS3MIP.NCAR.CESM2.land-hist.r1i1p1f1.Emon.fDeforestToAtmos.gn.v20190401|esgf-data.ucar.edu 

Error:
```
[2019-07-09 22:17:07,195: DEBUG/ForkPoolWorker-2] Using selector: EpollSelector
[2019-07-09 22:17:07,196: DEBUG/ForkPoolWorker-2] Using selector: EpollSelector
[2019-07-09 22:17:11,664: INFO/ForkPoolWorker-2] Creating manager with single file
[2019-07-09 22:17:11,664: INFO/ForkPoolWorker-2] compute_tasks.cdat.subset_func[4c8d086c-b5cd-4ed3-97f2-51e8963641ce]: Building 1 inputs
[2019-07-09 22:17:11,706: INFO/ForkPoolWorker-2] Subsetting the inputs
[2019-07-09 22:17:11,706: INFO/ForkPoolWorker-2] Opening file 'http://esgf-data.ucar.edu/thredds/dodsC/esg_dataroot/CMIP6/LS3MIP/NCAR/CESM2/land-hist/r1i1p1f1/Emon/fDeforestToAtmos/gn/v20190401/fDeforestToAtmos_Emon_CESM2_land-hist_r1i1p1f1_gn_185001-201512.nc'                                                                       
[2019-07-09 22:17:11,706: INFO/ForkPoolWorker-2] File has not been open before
[2019-07-09 22:17:11,706: INFO/ForkPoolWorker-2] Checking access with 'http://esgf-data.ucar.edu/thredds/dodsC/esg_dataroot/CMIP6/LS3MIP/NCAR/CESM2/land-hist/r1i1p1f1/Emon/fDeforestToAtmos/gn/v20190401/fDeforestToAtmos_Emon_CESM2_land-hist_r1i1p1f1_gn_185001-201512.nc.dds'                                                           
[2019-07-09 22:17:11,775: INFO/ForkPoolWorker-2] Current directory '/'
[2019-07-09 22:17:12,001: INFO/ForkPoolWorker-2] Retieving FileVariable 'fDeforestToAtmos'
[2019-07-09 22:17:12,002: INFO/ForkPoolWorker-2] Created input dask.array<array, shape=(1992, 192, 288), dtype=float32, chunksize=(100, 192, 288)>
[2019-07-09 22:17:12,003: INFO/ForkPoolWorker-2] Opening file 'http://esgf-data.ucar.edu/thredds/dodsC/esg_dataroot/CMIP6/LS3MIP/NCAR/CESM2/land-hist/r1i1p1f1/Emon/fDeforestToAtmos/gn/v20190401/fDeforestToAtmos_Emon_CESM2_land-hist_r1i1p1f1_gn_185001-201512.nc'                                                                       
[2019-07-09 22:17:12,003: INFO/ForkPoolWorker-2] Storing global attributes
[2019-07-09 22:17:12,003: INFO/ForkPoolWorker-2] Setting base units to 'days since 0001-01-01 00:00:00'
[2019-07-09 22:17:12,199: INFO/ForkPoolWorker-2] Storing temporal axis 'time' shape (1992,)
[2019-07-09 22:17:12,204: INFO/ForkPoolWorker-2] Storing spatial axis 'hist_interval' shape (2,)
[2019-07-09 22:17:12,204: INFO/ForkPoolWorker-2] Setting variable 'time_bnds' axes to ['time', 'hist_interval']
[2019-07-09 22:17:12,214: INFO/ForkPoolWorker-2] Storing variable 'time_bnds' shape (1992, 2)
[2019-07-09 22:17:12,215: INFO/ForkPoolWorker-2] Storing spatial axis 'lat' shape (192,)
[2019-07-09 22:17:12,215: INFO/ForkPoolWorker-2] Axis 'hist_interval' is not time and already discovered
[2019-07-09 22:17:12,215: INFO/ForkPoolWorker-2] Setting variable 'lat_bnds' axes to ['lat', 'hist_interval']
[2019-07-09 22:17:12,217: INFO/ForkPoolWorker-2] Storing variable 'lat_bnds' shape (192, 2)
[2019-07-09 22:17:12,218: INFO/ForkPoolWorker-2] Storing spatial axis 'lon' shape (288,)
[2019-07-09 22:17:12,218: INFO/ForkPoolWorker-2] Axis 'hist_interval' is not time and already discovered
[2019-07-09 22:17:12,218: INFO/ForkPoolWorker-2] Setting variable 'lon_bnds' axes to ['lon', 'hist_interval']
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Storing variable 'lon_bnds' shape (288, 2)
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Axis 'lat' is not time and already discovered
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Axis 'lon' is not time and already discovered
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Setting variable 'fDeforestToAtmos' axes to ['time', 'lat', 'lon']
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Storing variable 'fDeforestToAtmos' shape (1992, 192, 288)
[2019-07-09 22:17:12,220: INFO/ForkPoolWorker-2] Formatted dimension as (674899.4895833335, 735458.5, 1)
[2019-07-09 22:17:12,221: INFO/ForkPoolWorker-2] Converted domain to {'time': (674899.4895833335, 735458.5, 1)}
[2019-07-09 22:17:12,221: INFO/ForkPoolWorker-2] Mapping domain {'time': (674899.4895833335, 735458.5, 1)}
[2019-07-09 22:17:12,221: INFO/ForkPoolWorker-2] Mapped dimension 'time' shape (674899.4895833335, 735458.5, 1) -> slice(0, 1992, 1)
[2019-07-09 22:17:12,221: INFO/ForkPoolWorker-2] Subsetting axis 'hist_interval' shape (2,) -> (2,)
[2019-07-09 22:17:12,224: INFO/ForkPoolWorker-2] compute_tasks.cdat.subset_func[4c8d086c-b5cd-4ed3-97f2-51e8963641ce]: Failure '4c8d086c-b5cd-4ed3-97f2-51e8963641ce' [<compute_tasks.context.OperationContext object at 0x7fff38721d68>] {} AttributeError("'TransientAxis' object has no attribute 'units'",)                             
[2019-07-09 22:17:12,392: ERROR/ForkPoolWorker-2] Task compute_tasks.cdat.subset_func[4c8d086c-b5cd-4ed3-97f2-51e8963641ce] raised unexpected: AttributeError("'TransientAxis' object has no attribute 'units'",)                                                                                                                           
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/compute_tasks/cdat.py", line 311, in subset_func
    return process(context)
  File "/opt/conda/lib/python3.6/site-packages/compute_tasks/cdat.py", line 253, in process
    src, subset = input.subset(context.domain)
  File "/opt/conda/lib/python3.6/site-packages/compute_tasks/managers.py", line 480, in subset
    vars, axes = self.subset_variables_and_axes(domain, vars, axes, vars_axes)
  File "/opt/conda/lib/python3.6/site-packages/compute_tasks/managers.py", line 391, in subset_variables_and_axes
    axes[name] = axes[name].subAxis(i, j, k)
  File "/opt/conda/lib/python3.6/site-packages/cdms2/axis.py", line 1590, in subaxis
    setattr(newaxis, attname, getattr(self, attname))
AttributeError: 'TransientAxis' object has no attribute 'units'
```

Issue occurs when subset of axis "hist_interval"  is attempted, similar to subsetting bnds issues.

**Comment by jasonb5** [comment]
Fixed and tested on cluster, will push to production soon.

**Comment by jasonb5** [comment]
Fixed in devel.
