### ISSUE TITLE
Handle unsupport operands

### ISSUE THREAD

**Issue by jasonb5** [doutriaux1/wps_cwt#258]
Should capture exception and pass reasonable message back to user.

```python
[2020-05-22 21:55:53,309: DEBUG/ForkPoolWorker-29] compute_tasks.cdat.workflow[6e1c21f2-69ff-49d1-a4e9-f5eee60a5f4f]: Action keys ['jobs', 'status', 'create'] params {'job_pk': 44, 'status': 'ProcessFailed', 'exception': "unsupported operand type(s) for *: 'Array' and 'float'"} kwargs {}
[2020-05-22 21:55:53,488: DEBUG/ForkPoolWorker-29] compute_tasks.cdat.workflow[6e1c21f2-69ff-49d1-a4e9-f5eee60a5f4f]: Action keys ['user', 'process', 'create'] params {'user_pk': 2, 'process_pk': 1} kwargs {}
[2020-05-22 21:55:53,532: ERROR/ForkPoolWorker-29] Task compute_tasks.cdat.workflow[6e1c21f2-69ff-49d1-a4e9-f5eee60a5f4f] raised unexpected: TypeError("unsupported operand type(s) for *: 'Array' and 'float'")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/celery/app/base.py", line 487, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/compute_tasks/cdat.py", line 1030, in workflow
    interm = build_workflow(context)
  File "/opt/conda/lib/python3.7/site-packages/compute_tasks/cdat.py", line 657, in build_workflow
    interm[next.name] = process._process_func(context, next, *inputs, **params)
  File "/opt/conda/lib/python3.7/site-packages/compute_tasks/cdat.py", line 796, in process_dataset_or_const
    output = func(input[0], const)
  File "/opt/conda/lib/python3.7/site-packages/compute_tasks/cdat.py", line 1160, in <lambda>
    @bind_process_func(partial(process_dataset_or_const, func=lambda x, y: x * y))
  File "/opt/conda/lib/python3.7/site-packages/xarray/core/dataset.py", line 4816, in func
    ds = self._calculate_binary_op(g, other, join=align_type)
  File "/opt/conda/lib/python3.7/site-packages/xarray/core/dataset.py", line 4887, in _calculate_binary_op
    new_vars = {k: f(self.variables[k], other_variable) for k in self.data_vars}
  File "/opt/conda/lib/python3.7/site-packages/xarray/core/dataset.py", line 4887, in <dictcomp>
    new_vars = {k: f(self.variables[k], other_variable) for k in self.data_vars}
  File "/opt/conda/lib/python3.7/site-packages/xarray/core/variable.py", line 2036, in func
    if not reflexive
TypeError: unsupported operand type(s) for *: 'Array' and 'float'
```

**Comment by jasonb5** [comment]
The variable parameter was not defined.

**Comment by jasonb5** [comment]
Fixed in devel, produces better error message.
